### ISSUE TITLE
Nesting multiple blocks

### ISSUE THREAD

**Issue by kaelig** [chatrjr/single-responsibility-bem#1]
Hi,

Your concept is interesting on paper but when using very generic class names (title, button), afraid it prevents multiple blocks from being nested without having rules from the parent bleed on the children.

What's your take on this?

**Comment by chatrjr** [comment]
The blocks themselves are isolated since they're meant to stand on their own. For example, I wouldn't recommend doing anything like the following, because it ties the child block too closely to the context of the parent and removes its own.

```
.block {
    background: green;
    margin: 1em 0;
    padding: 2em;
    .__title {
        padding: 1em;
    }
    .__button {
        background: lime;
    }
    .nested-block {
        background: white;
        margin: 1em 0;
        padding: 1em;
        .__title {
            background: black;
            color: green;
            padding: 0.5em;
        }
        .__button {
            background: orange;
        }
    }
}
```

The resulting selector is too deep to encourage reuse of that block, whereas in the next example the blocks have the same level of specificity.

```
.block {
    background: green;
    margin: 1em 0;
    padding: 2em;
    .__title {
        border-radius: 8px;
        padding: 1em;
    }
    .__button {
        background: lime;
    }
}

.nested-block {
    background: white;
    margin: 1em 0;
    padding: 1em;
    .__title {
        background: black;
        color: green;
        padding: 0.5em;
    }
    .__button {
        background: orange;
    }
}
```

The problems start when the nested block doesn't have its own rules for elements it shares with the parent It will inherit the rules for those elements defined in its parent block, as you said. That gives the output you would expect.

This may or may not be a problem, but if the purpose of blocks are to encapsulate their elements, this definitely breaks that rule. Thanks for bringing it up. Now, as for what to do about it... I was thinking global elements. If you know certain parts of the interface will be reused (like a `.__button`, `.__title`, or `.__field`), group them with the other globals. That would solve one problem, but the parent block inheritance would still happen, because the selector is more specific and would overwrite the global.

If you give the child block its own element styling, that problem goes away as the parent's styles are overwritten. The problem being the styles that **aren't** overwritten are still carried to the child.

For the example, I have these globals.

```
/* =Global Elements
===================================== */

.__button {
    background: #06f;
    border: none;
    color: white;
    font-family: 'Titillium Web', sans-serif;
    font-size: 24px;
    padding: 0.5em;
    text-decoration: none;
}

.__title {
    background: red;
    color: white;
}
```

Coupled with the styling above for the blocks, I ended up with this result.

![issue 1 nested blocks - google chrome_046](https://f.cloud.github.com/assets/1988328/845311/dc3c5c0a-f3e4-11e2-9d49-d917c034282d.png)

Assuming we want some aspects of the parent to be represented by the child (let's say for a comment form we have a block `.comment-container` and a nested block of `.comments`), this could be desirable. And the parent and child blocks would still have their own context independent of each other while sharing the persisting global styles.

![selection_047](https://f.cloud.github.com/assets/1988328/845374/37789772-f3e6-11e2-892e-d64087aa87a4.png)

For the times where blocks are completely unrelated and the child inherits element styling from the parent... I'm gonna have to look into that.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
